'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан по шаблону.
'
'     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
'     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Counterparty
    Public Property Id As Integer
    Public Property Value As String
    Public Property INN As String
    Public Property Adress As String
    Public Property RegionId As Integer
    Public Property CityId As Integer

    Public Overridable Property City As City
    Public Overridable Property Region As Region
    Public Overridable Property Trades As ICollection(Of Trade) = New HashSet(Of Trade)
    Public Overridable Property Trades1 As ICollection(Of Trade) = New HashSet(Of Trade)

End Class
