'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан по шаблону.
'
'     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
'     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Good
    Public Property Id As Integer
    Public Property Value As String
    Public Property Kolvo As String
    Public Property Zena As Decimal
    Public Property CategoryId As Integer
    Public Property ManufacturerId As Integer

    Public Overridable Property Category As Category
    Public Overridable Property Manufacturer As Manufacturer
    Public Overridable Property Trades As ICollection(Of Trade) = New HashSet(Of Trade)

End Class
