'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан по шаблону.
'
'     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
'     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Manufacturer
    Public Property Id As Integer
    Public Property Value As String
    Public Property RegionId As Integer

    Public Overridable Property Goods As ICollection(Of Good) = New HashSet(Of Good)
    Public Overridable Property Region As Region

End Class
