'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан по шаблону.
'
'     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
'     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class TradeCompany2Entities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=TradeCompany2Entities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Categories() As DbSet(Of Category)
    Public Overridable Property Cities() As DbSet(Of City)
    Public Overridable Property Counterparties() As DbSet(Of Counterparty)
    Public Overridable Property Goods() As DbSet(Of Good)
    Public Overridable Property Manufacturers() As DbSet(Of Manufacturer)
    Public Overridable Property Regions() As DbSet(Of Region)
    Public Overridable Property sysdiagrams() As DbSet(Of sysdiagram)
    Public Overridable Property Trades() As DbSet(Of Trade)

End Class
